# Generated by Django 5.2.4 on 2025-07-10 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='plat_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='messagecontact',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 1, 42, 43, 620747, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='plat',
            field=models.CharField(default='Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
