# Generated by Django 5.2.4 on 2025-07-10 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_remove_commande_date_commande_remove_commande_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-10 14:40:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
